version: '3'
services:
  # The Application
  db:
    image: mysql:8.0
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: edaxpo
    volumes:
      - db_data:/var/lib/mysql
volumes:
    db_data:
        driver: local


