version: '3'
services:
  # The Application
  app:
    build:
      context: ./docker/php-fpm/8_dev
    working_dir: /var/www/
    user: "1000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www/
  web:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/perfcommons:/etc/nginx/conf.d/perfcommons
    links:
      - app
    ports:
      - 8030:80

